// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJeUn_mlckRlehi9rlTFcD45EHKjxWAl4',
    appId: '1:1021135554505:web:fef7ee0893956201584a18',
    messagingSenderId: '1021135554505',
    projectId: 'food-app-8f905',
    authDomain: 'food-app-8f905.firebaseapp.com',
    storageBucket: 'food-app-8f905.appspot.com',
    measurementId: 'G-21PK5G944V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxXdRwT5QYF0eObUjAoRiSdB79b5zyWsI',
    appId: '1:1021135554505:android:5aa58516b63aa8ca584a18',
    messagingSenderId: '1021135554505',
    projectId: 'food-app-8f905',
    storageBucket: 'food-app-8f905.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDg-OtMki0p_PXz-oJVfp0X8aukhhCo6Kc',
    appId: '1:1021135554505:ios:64de5f68a2d6e48a584a18',
    messagingSenderId: '1021135554505',
    projectId: 'food-app-8f905',
    storageBucket: 'food-app-8f905.appspot.com',
    iosClientId: '1021135554505-7ncu0jr4no41a1abui6d092o07ru6rgo.apps.googleusercontent.com',
    iosBundleId: 'com.naveenchand.foodAppUi',
  );
}
